version: '3.8'
services:
  redis:
    image: redis:7.0.2-alpine
    ports:
      - '6379:6379'
    restart: always
  api:
    image: nethermind-api
    build:
      dockerfile: ./Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
    command: yarn start:dev
